
DRUG_SEARCH_FORM =  {
	 "search_detail":"Y",
	 "proTabState": 0,
	 "NoProTabState": 0,
	 "proYN":"",
	 "icode":"",
	 "input_drug_nm": "",
	 "search_sunb1":"",
	 "search_drugnm_initial":"",
	 "search_drugnm_initial":"",
	 "search_drugnm_initial":"",
	 "search_drugnm_initial":"",
	 "search_drugnm_initial":"",
	 "search_drugnm_initial":"",
	 "search_drugnm_initial":"",
	 "search_drugnm_initial":"",
	 "search_drugnm_initial":"",
	 "search_drugnm_initial":"",
	 "search_drugnm_initial":"",
	 "search_drugnm_initial":"",
	 "search_drugnm_initial":"",
	 "search_drugnm_initial":"",
	 "drug_nm_mode":"field",
	 "drug_nm":"",
	 "match_value":"",
	 "sunb_equals1":"",
	 "sunb_equals2":"",
	 "sunb_equals3":"",
	 "sunb_where1":"and",
	 "sunb_where2":"and",
	 "input_upsoNm":"",
	 "search_effect":"",
	 "cbx_sunbcnt": 0,
	 "cbx_sunbcnt_mode": 0,
	 "cbx_bohtype":"",
	 "cbx_bohtype":"",
	 "cbx_bohtype":"",
	 "cbx_bohtype":"",
	 "cbx_bohtype_mode": 0,
	 "cbx_class": 0,
	 "cbx_class":"",
	 "cbx_class":"",
	 "cbx_class":"",
	 "cbx_class_mode": 0,
	 "search_bohcode":"",
	 "anchor_dosage_route_hidden":"",
	 "anchor_form_info_hidden":"",
	 "mfds_cdWord":"",
	 "mfds_cd":"",
	 "cbx_narcotic":"",
	 "cbx_narcotic":"",
	 "cbx_narcotic":"",
	 "cbx_narcotic":"",
	 "cbx_narcotic":"",
	 "cbx_narcotic_mode": 0,
	 "kpic_atc_nm":"",
	 "kpic_atc_nm_opener":"",
	 "atccode_name":"",
	 "atccode_val":"",
	 "atccode_val_opener":"",
	 "input_hiraingdcd":"",
	 "cbx_bio":"",
	 "cbx_bio":"",
	 "cbx_bio":"",
	 "cbx_bio":"",
	 "cbx_bio_mode": 0,
}

DRUG_SEARCH_MORE_FORM = {
	"input_drug_nm": "",
	"search_sunb1": "",
	"search_sunb2": "",
	"search_sunb3": "",
	"search_drugnm_initial": ", , , , , , , , , , , , , ",
	"drug_nm_mode": "field",
	"drug_nm": "",
	"sunb_equals1": "",
	"sunb_equals2": "",
	"sunb_equals3": "",
	"sunb_where1": "and",
	"sunb_where2": "and",
	"input_upsoNm": "",
	"search_effect": "",
	"cbx_sunbcnt": 0,
	"cbx_sunbcnt_mode": 0,
	"cbx_bohtype": "0, , , ",
	"cbx_bohtype_mode": 0,
	"cbx_class": "0, , , ",
	"cbx_class_mode": 0,
	"search_bohcode": "",
	"anchor_dosage_route_hidden": "",
	"anchor_form_info_hidden": "",
	"mfds_cd": "",
	"mfds_cdword": "",
	"cbx_narcotic": "0, , , , ",
	"cbx_narcotic_mode": 0,
	"kpic_atc_nm": "",
	"kpic_atc_nm_opener": "",
	"atccode_name": "",
	"atccode_val": "",
	"atccode_val_opener": "",
	"input_hiraingdcd": "",
	"cbx_bio": "0, , , ",
	"cbx_bio_mode": 0,
	"icode": "",
	"fixed_cnt": None,
	"search_detail": "Y",
	"TabState": 0,
	"proYN": "Y",
	"pageNo": 1,
	"rowLength": 100,
	"inner_search_word": "",
	"inner_search_flag": "drug_name",
	"viewmode": "",
	"listup": 10,
	"more": ""
}